server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${campus.canteen.datasource.driver-class-name}
      url: jdbc:mysql://${campus.canteen.datasource.host}:${campus.canteen.datasource.port}/${campus.canteen.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${campus.canteen.datasource.username}
      password: ${campus.canteen.datasource.password}
  redis:
    host: ${campus.canteen.redis.host}
    port: ${campus.canteen.redis.port}
    password: ${campus.canteen.redis.password}
    database: ${campus.canteen.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.campus.canteen.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      campus:
        canteen:
          mapper: debug
          service: info
          controller: info

campus:
  canteen:
    jwt:
      # 设置jwt签名加密时使用的秘钥
      admin-secret-key: itcast
      # 设置jwt过期时间
      admin-ttl: 720000000
      # 设置前端传递过来的令牌名称
      admin-token-name: token
      user-secret-key: itshin
      user-ttl: 720000000
      user-token-name: authentication

    # 阿里云OSS配置
    alioss:
      endpoint: ${campus.canteen.alioss.endpoint}
      accessKeyId: ${campus.canteen.alioss.accessKeyId}
      accessKeySecret: ${campus.canteen.alioss.accessKeySecret}
      bucketName: ${campus.canteen.alioss.bucketName}

    wechat:
      appid: ${campus.canteen.wechat.appid}
      secret: ${campus.canteen.wechat.secret}